# Generated by Django 4.2.30 on 2026-04-16 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_id', models.CharField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('rating', models.FloatField(default=0.0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('stock_status', models.CharField(blank=True, max_length=120)),
                ('book_url', models.URLField(unique=True)),
                ('image_url', models.URLField(blank=True)),
                ('scraped_from', models.CharField(default='books.toscrape.com', max_length=120)),
                ('summary', models.TextField(blank=True)),
                ('genre_prediction', models.CharField(blank=True, max_length=120)),
                ('recommendation_pitch', models.TextField(blank=True)),
                ('sentiment_label', models.CharField(blank=True, max_length=40)),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('key_themes', models.JSONField(blank=True, default=list)),
                ('highlight_quote', models.TextField(blank=True)),
                ('processing_notes', models.TextField(blank=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('citations', models.JSONField(blank=True, default=list)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('cache_hit', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='books.book')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk_index', models.PositiveIntegerField()),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='books.book')),
            ],
            options={
                'ordering': ['book_id', 'chunk_index'],
                'unique_together': {('book', 'chunk_index')},
            },
        ),
    ]
